### ISSUE TITLE
Video iframe responsiveness

### ISSUE THREAD

**Issue by martinhalik** [martinenka/kurz#3]
It should be responsive. but you will probably have to calculate the height via JS? right?

**Comment by filipdanisko** [comment]
CZ: Tohle se dá vyřešit pouze pomocí CSS. Měl jsem tam ale ještě jeden problém, nezobrazovalo se mi video kvuli jiné doméně, tak jsem vzal SRC toho vide a vložil jej do nativního <video> elementu. Na to jsem pak jen aplikoval width: 100% a height: auto;
